"""
dataloader.py — PyTorch Dataset and DataLoader factory.
"""

from pathlib import Path
from typing import Literal

import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

from config import (
    IMG_SIZE, BATCH_SIZE, NUM_WORKERS, PIN_MEMORY, SPLITS_CSV,
    NORMALIZE_MEAN, NORMALIZE_STD,
    AUG_HFLIP_PROB, AUG_ROTATION_DEG, AUG_BRIGHTNESS, AUG_CONTRAST,
    CROP_SCALE_MIN,
)


def get_train_transforms() -> transforms.Compose:
    """
    Augmentation pipeline for the training split.

    Design notes for X-ray images:
    - RandomResizedCrop: zooms into a random 60–100% area region before
      resizing, forcing the model to generalise to different scales/offsets.
      Much stronger than a plain Resize which always sees the same field-of-view.
    - HorizontalFlip: valid — left/right forearm views are symmetric
    - NO vertical flip — anatomical orientation (proximal/distal) matters clinically
    - Rotation ±15°: mimics real positioning variation in the X-ray room
    - Brightness/contrast jitter: simulates exposure variation across machines
    - NO elastic deformation — fracture lines are subtle; aggressive spatial
      distortion risks removing or fabricating pathology
    - Grayscale → 3-channel: pretrained models expect 3-channel input;
      repeating the single channel 3× preserves intensity while satisfying the API
    """
    return transforms.Compose([
        transforms.Grayscale(num_output_channels=3),
        transforms.RandomResizedCrop(IMG_SIZE, scale=(CROP_SCALE_MIN, 1.0)),
        transforms.RandomHorizontalFlip(p=AUG_HFLIP_PROB),
        transforms.RandomRotation(degrees=AUG_ROTATION_DEG),
        transforms.ColorJitter(
            brightness=AUG_BRIGHTNESS,
            contrast=AUG_CONTRAST,
        ),
        transforms.ToTensor(),
        transforms.Normalize(mean=NORMALIZE_MEAN, std=NORMALIZE_STD),
    ])


def get_val_transforms() -> transforms.Compose:
    """
    Deterministic pipeline for val/test — no augmentation.

    Resize to slightly larger than IMG_SIZE then centre-crop — the standard
    ImageNet evaluation protocol. Avoids the minor distortion of squeezing
    a non-square image directly to IMG_SIZE × IMG_SIZE.
    """
    eval_size = int(IMG_SIZE * 256 / 224)   # e.g. 256 for IMG_SIZE=224
    return transforms.Compose([
        transforms.Grayscale(num_output_channels=3),
        transforms.Resize(eval_size),
        transforms.CenterCrop(IMG_SIZE),
        transforms.ToTensor(),
        transforms.Normalize(mean=NORMALIZE_MEAN, std=NORMALIZE_STD),
    ])


class FractureDataset(Dataset):
    """
    PyTorch Dataset for binary fracture classification.

    Args:
        splits_csv: Path to splits.csv generated by dataset.py
        split:      'train', 'val', or 'test'
        transform:  torchvision Compose pipeline to apply
    """

    def __init__(
        self,
        splits_csv: Path,
        split: Literal["train", "val", "test"],
        transform: transforms.Compose,
    ):
        df = pd.read_csv(splits_csv)
        self.df = df[df["split"] == split].reset_index(drop=True)
        self.transform = transform
        assert len(self.df) > 0, f"No records found for split='{split}' in {splits_csv}"

    def __len__(self) -> int:
        return len(self.df)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, int]:
        row = self.df.iloc[idx]
        # convert("L") normalises to 8-bit grayscale regardless of source bit depth
        image = Image.open(row["path"]).convert("L")
        label = int(row["label_id"])  # 0=normal, 1=fracture
        if self.transform:
            image = self.transform(image)
        return image, label

    def label_counts(self) -> dict:
        return self.df["label"].value_counts().to_dict()


def get_dataloaders(splits_csv: Path = SPLITS_CSV) -> dict[str, DataLoader]:
    """
    Build and return train / val / test DataLoaders.

    Returns:
        dict with keys 'train', 'val', 'test'
    """
    train_ds = FractureDataset(splits_csv, "train", get_train_transforms())
    val_ds   = FractureDataset(splits_csv, "val",   get_val_transforms())
    test_ds  = FractureDataset(splits_csv, "test",  get_val_transforms())

    print(f"Train : {len(train_ds):,} images  {train_ds.label_counts()}")
    print(f"Val   : {len(val_ds):,} images  {val_ds.label_counts()}")
    print(f"Test  : {len(test_ds):,} images  {test_ds.label_counts()}")

    persistent = NUM_WORKERS > 0

    train_dl = DataLoader(
        train_ds,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=persistent,
        drop_last=True,   # avoids unstable BatchNorm on tiny last batch
    )
    val_dl = DataLoader(
        val_ds,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=persistent,
    )
    test_dl = DataLoader(
        test_ds,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        persistent_workers=persistent,
    )

    return {"train": train_dl, "val": val_dl, "test": test_dl}
