services:
  - type: web
    name: fracture-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: >
      pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu --quiet &&
      pip install -r api/requirements.txt
    startCommand: bash -c "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: HF_REPO_ID
        value: VenthanVi/fracture-detection
      - key: MODEL_NAME
        value: tf_efficientnetv2_m
      - key: IMG_SIZE
        value: "480"
